language: generic
sudo: false
dist: trusty

branches:
  except:
    - /^deploy-.*$/

cache:
  apt: true
  directories:
    - build/resources/
    - carl/

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - g++-6
      - libcln-dev
      - libeigen3-dev
      - libgmp-dev
      - libgtest-dev
      - openjdk-7-jdk
      - time
      - uuid-dev

matrix:
  include:
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=DEPLOY
    - os: osx
      osx_image: xcode8.3
      env: CC=clang CXX=clang++


before_install:
  - cd .ci/ && source setup_travis.sh && cd ../

script:
  - source .ci/build_travis.sh

deploy:
  provider: script
  skip_cleanup: true
  script: bash .ci/deploy_travis.sh
